docs: update documentation for resolve CORS and CSP errors
halo-sigs/plugin-umami pull request #17
Opened 2023-11-23 11:05 UTC by V-Official-233

更新解决 CORS 和 CSP 异常的文档。

```release-note
None
```

2023-11-23 14:36 UTC, ruibaby requested changes

2023-11-23 14:36 UTC, ruibaby commented on README.md
> +2. 添加环境变量 `ALLOWED_FRAME_URLS` 内容请写您的halo地址，例：
```suggestion
2. 方式 2：为 Umami 的容器添加环境变量 `ALLOWED_FRAME_URLS`，值为 Halo 的访问地址，例：
```

2023-11-23 14:36 UTC, ruibaby commented on README.md
> +> 此方法适用于在任何平台部署的Umami
```suggestion
> 此方式适用于 Umami 2.3.0 以上版本。
```

2023-11-23 14:36 UTC, ruibaby commented on README.md
> +2. 添加环境变量 `ALLOWED_FRAME_URLS` 内容请写您的halo地址，例：
这个应该不是第 2 个 FAQ 内容，应该是遇到了 CORS 和 CSP 错误的补充，所以可能需要放在序号 1 中。

2023-11-23 14:36 UTC, ruibaby commented on README.md
> +> Umami 的站点地址 例：https://umami.halo.run
建议另起一个序号，而不是引用，例如：

4. 进入插件设置页面，配置以下信息：
  - Umami 站点地址：balabala
  - 脚本名称：balabala
  - ...

2023-11-23 14:57 UTC, VOfficial404 commented on README.md
> +> Umami 的站点地址 例：https://umami.halo.run
收到，明日如果有时间我继续改进一下

2023-11-26 02:11 UTC, ruibaby approved these changes
/lgtm

2023-11-26 02:12 UTC, merged